### PR TITLE
Issue 135 bootstrap superuser

### PR DESCRIPTION
**Pull request by steveellis**
This should complete the work needed for bootstrapping a superuser. It works, and I'm able to login and get a token. It runs it as a job using the container that exists for that from folio-helm.

The superuser stuff is important even if we end up importing all of our user data from an existing database. This is because the script that creates the superuser is also the same script that applies permissions to the superuser when a new mod is installed. So ideally the bootstrap superuser script would be run every time the modules change (with the `--onlyperms` param. But the idea of a k8s job that runs every time a stack changes is a bit foreign to pulumi. As a workaround for this we may want to consider running `pulumi destroy --target <job>` first for jobs which we want to run each time something changes.

This also ads some notes to the readme for dealing with k8s jobs in pulumi with some of the ideas above.

I also made some changes to the design of what I'm now calling the "deployment yaml". I added a property there called `createSuperuser` which if true, will attempt to create the superuser. This is because the perl script isn't idempotent for _creating_ the superuser. If you run it more than once (without the `--onlyperms` command), it will put folio install in an unstable state. It is idempotent when running it with `--onlyperms` however. The workflow is something like the following:
* Set it manually to true when you're installing from scratch. If you forget you can always delete and recreate the job.
* Set it manually to false for all subsequent runs/updates to an install.

I think this is in line with how we're thinking about this config yaml. It's your hand-hold for the folio stuff that exists outside fo the stack. Throughout there are comments for how to use this.

### CODE REVIEW

**Comment by steveellis** [comment]
Have made various attempts documented in comments in index.ts for how to fix the timeout error I'm continuing to get when trying to register modules. See commit messages for details. The main issue is when running the jobs this request is timing out causing the registration to fail:
```
2021-12-24T16:10:38,090 ERROR   HttpResponse    HTTP response code=400 msg=POST request for mod-permissions-5.14.2 /_/tenantpermissions failed with 400: Timeout
```
Have explored:
* Increasing pg's connection limit
* Setting the `DB_QUERYTIMEOUT` environment var

**Comment by steveellis** [comment]
I have just tenant module registration work well again. It may be 1) because I redeployed okapi (deleted and recreated via pulumi), 2) the setting of `DB_MAXPOOLSIZE` in the secret. It is unclear to me if this variable was present prior to the change (a default setting) or was due to my change. More testing needed.

**Comment by steveellis** [comment]
I have now created and destroyed the stack multiple times and have some insights into what isn't working. These items are:
* The items immediately following creating the cluster always fail but succeed on second runs. For example create-database and kafka. I believe this is due to how I'm passing references around in the `FolioDeployment` object -- which is created when the stack created. References to things like namespaces and other objects like the cluster aren't being updated as I expected.
* Module registration jobs as they currently stand "work" but must be destroyed and re-run up to 7 or 8 times. This is obviously not ideal and likely due to the fact that each job has no mechanism to wait to complete prior to kicking off the next job, so modules that depend on other modules  prior to the previous job completing. To fix this we need to check that the module has been successfully registered prior to registering the next.

Bootstrapping the super user has been known to work, but only only after all modules have registered successfully.

**Comment by steveellis** [comment]
The two issues noted above appear to have been solved. The problem with the create-database job was simply that it was lacking a provider.

Module registration appears to have been solved by using [init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers), a k8s concept that has two important characteristics: you specify a set of containers that must run before another container runs, and, crucially, each init container waits for the prior container in the list to finish before it begins. After this change, in my test I saw 0 okapi errors and all 53 modules were registered on the first run.

**Review by jwfuller — APPROVED** [review]

**Comment by steveellis** [comment]
One last note: I moved the references to the cluster and the namespace out of the `FolioDeployment` class and refactored a lot of methods because of that. I was worried that the references to these objects weren't being updated. I don't think this ultimately was a factor to some of the troubles I had, but I think that it somewhat better to have only static items in `FolioDeployment`.

**Pull request merged**
